name: "Bug Report"
description: "Report a defect or unexpected behavior"
title: "[BUG] "
labels: ["type: bug"]
body:
- type: textarea
id: description
attributes:
label: Bug Description
description: "Clear, concise description of the bug"
validations:
required: true
- type: textarea
id: steps
attributes:
label: Steps to Reproduce
value: |
1. Go to '...'
2. Click on '...'
3. Observe '...'
validations:
required: true
- type: textarea
id: expected
attributes:
label: Expected Behavior
validations:
required: true
- type: textarea
id: actual
attributes:
label: Actual Behavior
validations:
required: true
- type: dropdown
id: severity
attributes:
label: Severity
options:
- "🔴 Critical — System down / data loss"
- "🔴 High — Major feature broken"
- "🔴 Medium — Workaround available"
- "🔴 Low — Cosmetic / minor"
validations:
required: true
- type: textarea
id: environment
attributes:
label: Environment
value: |
- OS:
- Browser:
- Version/Commit:
