name: "🔴 Spike / Research"
description: "Time-boxed research or proof-of-concept"
title: "[SPIKE] %short title%"
labels: ["type: spike"]
body:
  - type: textarea
    id: question
    attributes:
      label: "Research Question"
      description: "What are we trying to learn or validate?"
    validations:
      required: true

  - type: input
    id: timebox
    attributes:
      label: "Time Box"
      description: "Maximum hours to spend on this"
      placeholder: "4 hours"
    validations:
      required: true

  - type: textarea
    id: deliverable
    attributes:
      label: "Expected Deliverable"
      description: "What artifact or decision should come out of this?"
      placeholder: "A short write-up with recommendation, a proof-of-concept, etc."
    validations:
      required: true
