name: "User Story"
description: "A feature described from the user's perspective"
title: "[STORY] Auth: Register / Login / Logout"
labels: ["type: user-story", "area: backend"]

body:
  - type: textarea
    id: story
    attributes:
      label: User Story
      description: "Describe the story in the format: As a..., I want..., so that..."
      value: |
        As a student,
        I want to register and log in,
        so that I can access practice exams and save progress.
    validations:
      required: true

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: "Define the conditions that must be met"
      value: |
        - [ ] Registration endpoint creates a user and returns a JWT.
        - [ ] Login endpoint returns a JWT for valid credentials.
        - [ ] Frontend stores JWT and sends it in the Authorization header.
        - [ ] Logout clears stored token.
        - [ ] Roles `user` and `admin` are enforced.
    validations:
      required: true

  - type: textarea
    id: technical-notes
    attributes:
      label: Technical Notes
      description: "Any implementation considerations"
      value: |
        - Add `role` field to User model with enum: ["user","admin"].
        - Use bcryptjs for hashing.
        - Use jsonwebtoken for JWT.
        - Implement auth middleware.
        - Add integration tests.

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - "🔴 High"
        - "🟡 Medium"
        - "🟢 Low"
    validations:
      required: true

  - type: input
    id: story-points
    attributes:
      label: Story Points
      description: "Estimated complexity (1, 2, 3, 5, 8, 13)"
      placeholder: "3"
